#! /bin/bash

# This is the install script for GUV. 
# If started with option "-make" the binaries will not be built.

version=001

set -e

#source_script_dir=scripts

dest_conf_dir=$HOME/.guv
dest_script_dir=$HOME/bin
echo "GUV installer version" $version

#procedure_copy_script()
#	{
#	name=$1
#	#echo "-" $name
#	cp $source_script_dir/$name $dest_script_dir
#	}

procedure_operator_confirmation()
	{
	echo -n "proceed ? (y/n): "
	read key
	echo
	[ ! $key = "y" ] && 
		{
		echo "installation aborted by operator"
		exit 1
		}
	}

procedure_make()
	{
	target=$1
	echo "-" $target
	cd src/$target # change into source dir
	make clean # clean up
	make # compile
	make install # install
	make clean # clean up
	cd - # change back to origin dir
	}

[ ! -e $dest_conf_dir ] && 
	{
	echo "creating hidden configuration directory" $dest_conf_dir "..."
	cp -R conf/.guv $HOME
	}
#CS: ask user if configuration directory should be updated.

#echo "copying script files in" $dest_script_dir "..."
#echo "WARNING ! Already existing script files residing there will be overwritten !"
#procedure_operator_confirmation
	
#procedure_copy_script yxz


if [ ! "$1" = "-make" ] 
	then
		echo "compiling and installing ..."
		set +e
		procedure_make guv
fi

echo done
exit
